# Generated by Django 4.1.3 on 2022-12-10 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('NA', 'NA')], default='NA', max_length=6)),
                ('district', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('govt_id_type', models.CharField(default='', max_length=64)),
                ('govt_id_no', models.CharField(default='', max_length=64)),
                ('modified_datetime', models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 41, 879121, tzinfo=datetime.timezone.utc))),
                ('added_datetime', models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 41, 879121, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerDetails',
            fields=[
                ('reviewer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=30)),
                ('modified_datetime', models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 41, 879121, tzinfo=datetime.timezone.utc))),
                ('added_datetime', models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 41, 879121, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ownership', models.CharField(choices=[('JOINT', 'JOINT'), ('INDIVIDUAL', 'INDIVIDUAL')], default='NA', max_length=10)),
                ('category', models.CharField(choices=[('Commerical', 'Commerical'), ('Residential', 'Residential')], default='NA', max_length=30)),
                ('application_date', models.DateField(null=True)),
                ('load_applied', models.IntegerField()),
                ('approval_date', models.DateField(null=True)),
                ('modified_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Connection Released', 'Connection Released'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='NA', max_length=30)),
                ('reviewer_comments', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicationManagement.applicantdetails')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicationManagement.reviewerdetails')),
            ],
        ),
    ]
