# Generated by Django 4.1.3 on 2022-12-10 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='added_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 50, 401225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='modified_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 50, 401225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reviewerdetails',
            name='added_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 50, 401225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reviewerdetails',
            name='modified_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 50, 50, 401225, tzinfo=datetime.timezone.utc)),
        ),
    ]
